name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: source/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update git submodules
      run: git submodule update --init --recursive
    - name: make
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: vrchat-osc
        path: source/vrchat-osc
        if-no-files-found: error
        retention-days: 7
